name: Python Package

on:
  push:
  pull_request:

env:
  RUFF_VERSION: "0.7.1"
  MYPY_VERSION: "1.13.0"

jobs:
  static_code_analysis:
    name: Ruff
    runs-on: ubuntu-latest
    container:
      image: python:3.11-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: python3 -m pip install ruff==${{ env.RUFF_VERSION }}
      - name: Run Ruff
        run: python3 -m ruff check src

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: static_code_analysis
    container:
      image: python:3.11-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Install build
        run: python3 -m pip install build
      - name: Build package
        run: python3 -m build
      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/*.whl
            dist/*.tar.gz
          retention-days: 1

  type_checks:
    name: MyPy
    runs-on: ubuntu-latest
    needs: build
    container:
      image: python:3.11-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Install mypy and dependencies
        run: |
          python3 -m pip install mypy==${{ env.MYPY_VERSION }}
          python3 -m pip install -r requirements/typing.txt
          python3 -m pip install dist/*.whl
      - name: Run mypy
        run: python3 -m mypy src
